config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users
  resources :genres, only: [:index, :show] do 
    resources :contents, only: [:index, :create, :show, :destroy] do
      resources :details, only: [:index, :create, :destroy]
    end
  end
  resources :users, only: [:show, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
  validates :title, presence: true
  belongs_to :genre
  has_many :details, dependent: :destroy
end

app/models/detail.rb
class Detail < ApplicationRecord
  belongs_to :genre
  belongs_to :content

  validates :detail, presence: true
  mount_uploader :image, ImageUploader

end

app/models/genre.rb
class Genre < ApplicationRecord
  belongs_to :user, optional: true
  has_many :contents
  has_many :details
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :genres
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_genre
  
  def index
    @content = Content.new
    @contents = @genre.contents.includes(:genre).order("created_at DESC").page(params[:page]).per(9)
  end

  def create
    @content = @genre.contents.new(content_params)
    if @content.save
      respond_to do |format|
        format.html { redirect_to genre_contents_path(@genre,@content)}
        format.json { render json: @content}
      end
    else
      @contents = @genre.contents.includes(:genre)
      flash.now[:alert] = 'タイトルを入力してください。'
      render :index
    end
  end

  def destroy
    content = Content.find(params[:id])
    content.destroy
    redirect_to genre_contents_path(@genre,@content)
  end
  
  def show
    @content = Content.find(params[:id])
  end

  private

  def content_params
    params.require(:content).permit(:title).merge(user_id: current_user.id)
  end

  def set_genre
    @genre = Genre.find(params[:genre_id])
  end
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  before_action :set_genre
  before_action :set_content

  
  def index
    @detail = Detail.new
    @details = @content.details.includes(:genre, :content).order("created_at DESC").page(params[:page]).per(12)
  end

  def create
    @detail = @content.details.new(detail_params)
    if @detail.save
      respond_to do |format|
        format.html {redirect_to  genre_content_details_path(@genre,@content)}
        format.json
      end
    else
      @details = @content.details.includes(:genre, :content)
      flash.now[:alert] = '詳細を入力してください。'
      render :index
    end
  end

  def destroy
    detail = Detail.find(params[:id])
    detail.destroy
    redirect_to  genre_content_details_path(@genre,@content)
  end

  private

  def detail_params
    params.require(:detail).permit(:detail, :image, :text).merge(genre_id: @genre.id, content_id: @content.id, user_id: current_user.id)
  end

  def set_genre
    @genre = Genre.find(params[:genre_id])
  end

  def set_content
    @content = Content.find(params[:content_id])
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contents/index.html.haml
.contents
  .form
    = form_for [@genre, @content] do |f|
      = f.text_field :title, class: 'form__content', placeholder: '追加したいタイトル名を入力', autocomplete: 'off'
      .form__mask
      = f.submit 'Send', class: 'form__submit'
    %ul.uk-list.uk-list-striped
      - @contents.each do |content| 
        -if user_signed_in? && current_user.id == content.user_id
          %li.list
            = link_to content.title, genre_content_details_path(@genre.id, content.id)
            .content-destroy
              = link_to genre_content_path(@genre.id, content.id), method: :delete, data: { confirm: '本当に消しますか?' } do
                = icon('far','times-circle')
    = paginate(@contents)

app/views/details/index.html.haml
.details-main
  .details-header
    .details-header__name
      = @content.title
    .details-header__form
      = form_for [@genre, @content, @detail] do |f|
        .input-box__top
          = f.text_field :detail, class: 'input-box__top__detail', placeholder: '詳細を入力してください',autocomplete: 'off'
          = f.label :image, class: 'input-box__top__image' do
            = icon('fas','image')
            = f.file_field :image, class: 'input-box__top__image__file'
        .input-box__bottom
          = f.text_field :text, class: 'input-box__bottom__text', placeholder: 'このfavoriteに一言',autocomplete: 'off'
        = f.submit 'Send', class: 'input-box__bottom__send-btn'
  %ul.main
    - @details.each do |detail|
      -if user_signed_in? && current_user.id == detail.user_id
        %li.detail
          %strong.detail_name
            =detail.detail
          .detail_image
            -if detail.image.blank?
              %img(src="/assets/default-565b88a8c2fade1693a3bcaf71d4ec98c88c56b1a1ec7d2d725880225333d61b.jpg" alt="Default")
            -else
              =image_tag detail.image_url
          %p.detail_text
            =detail.text
          .detail_destroy
            = link_to genre_content_detail_path(@genre,@content, detail), method: :delete, data: { confirm: '本当に消しますか?' } do
              = icon('far','times-circle')
    = paginate(@details)

app/views/genres/index.html.haml
.wrapper
  .genres
    .book
      =link_to "BOOK", genre_contents_path(genre_id: 1)
    .music 
      =link_to "MUSIC",genre_contents_path(genre_id: 2)
    .movie 
      =link_to "MOVIE",genre_contents_path(genre_id: 3)
    .youtube 
      =link_to "YOUTUBE",genre_contents_path(genre_id: 4)

app/views/homes/_main.haml
.main
  .intro
    .copy 
      %strong 自分だけのお気に入り部屋を作成しよう
    .text
      %p favoritesは、お気に入りの音楽や本などを保存できるサイトです。懐かしのあの曲も、昔読んだあの本もいつでも振り返ることのできる場所を提供します。
  .about
    - if user_signed_in?
      .new-favorites
        %strong my favorites作成
        =link_to "ジャンルを選択", genres_path
    - else
      .create-favorites
        %strong my favorites作成にはログインが必要です。

app/views/homes/index.html.haml
.wrapper
  = render "main"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Favorites
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    .header
      .header__name
        =link_to "favorites", root_path
        .header__right-box
          - if user_signed_in?
            .header__right__box__back
              =link_to "Back", onclick="javascript:history.back();"
            .header__right__box__user
              =link_to "#{current_user.name}",edit_user_path(current_user)
          -else
            .header__right-box__new
              =link_to "新規登録", new_user_registration_path
            .header__right-box__login
              =link_to "ログイン", new_user_session_path
    = yield

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'